import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import TopBar from "../components/TopBar";
import { calculateLeave, formatDate } from "../utils/leaveCalculator";
import type { LeaveType, LeaveResult, Holiday } from "../utils/leaveCalculator";
import { fetchHolidays, IRISH_PUBLIC_HOLIDAYS } from "../utils/holidays";
import { Office365OutlookService } from "../generated/services/Office365OutlookService";
import { Office365UsersService } from "../generated/services/Office365UsersService";
import "./CalculatorPage.css";

const HR_EMAIL = "maciej.topczewski@gds.ey.com";

function buildBreakdownEmailHtml(
  result: LeaveResult,
  leaveType: string,
  senderName: string,
  senderEmail: string,
  senderJobTitle: string,
  senderDepartment: string
): string {
  const typeLabel = leaveType === "maternity" ? "Maternity" : "Paternity";

  const periodsRows = result.periods
    .map(
      (p) =>
        `<tr>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;font-weight:600;color:#2E2E38;">${p.label}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;color:#555;">${formatDate(p.startDate)}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;color:#555;">${formatDate(p.endDate)}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;text-align:center;font-weight:600;color:#2E2E38;">${p.calendarDays}</td>
        </tr>`
    )
    .join("");

  const holidaysRows =
    result.publicHolidaysInPeriod.length > 0
      ? result.publicHolidaysInPeriod
          .map(
            (h) =>
              `<tr>
                <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#2E2E38;">${formatDate(h.date)}</td>
                <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#555;">${h.name}</td>
              </tr>`
          )
          .join("")
      : "";

  const holidaysSection =
    result.publicHolidaysInPeriod.length > 0
      ? `<h3 style="color:#2E2E38;font-size:14px;margin:24px 0 8px;text-transform:uppercase;letter-spacing:0.5px;">Public Holidays During Leave (${result.publicHolidaysInPeriod.length})</h3>
         <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border:1px solid #eee;border-radius:4px;border-collapse:collapse;">
           <tr style="background:#FAFAFA;">
             <th style="padding:8px 12px;text-align:left;font-size:11px;color:#888;text-transform:uppercase;border-bottom:1px solid #eee;">Date</th>
             <th style="padding:8px 12px;text-align:left;font-size:11px;color:#888;text-transform:uppercase;border-bottom:1px solid #eee;">Holiday</th>
           </tr>
           ${holidaysRows}
         </table>
         <p style="color:#888;font-size:12px;font-style:italic;margin:8px 0 0;">Each public holiday extends the leave period by one additional day.</p>`
      : "";

  return `
<div style="font-family:'Segoe UI',Arial,sans-serif;max-width:640px;margin:0 auto;">
  <div style="background-color:#2E2E38;padding:24px 32px;border-bottom:4px solid #FFE600;">
    <span style="color:#FFE600;font-size:24px;font-weight:700;letter-spacing:2px;">EY</span>
    <span style="color:rgba(255,255,255,0.4);margin:0 12px;">|</span>
    <span style="color:rgba(255,255,255,0.8);font-size:14px;">Family Leave Calculator</span>
  </div>
  <div style="background-color:#ffffff;padding:32px;border:1px solid #e0e0e0;border-top:none;">
    <h2 style="color:#2E2E38;font-size:18px;margin:0 0 8px;font-weight:600;">${typeLabel} Leave - Provisional Breakdown</h2>
    <p style="color:#6C6C6C;font-size:13px;margin:0 0 24px;border-bottom:1px solid #eee;padding-bottom:16px;">
      This breakdown was generated by the Family Leave Calculator and submitted for HR review.
    </p>

    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:24px;background:#FAFAFA;border:1px solid #eee;border-radius:4px;border-collapse:collapse;">
      <tr>
        <td style="padding:12px 16px;border-bottom:1px solid #eee;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;">Employee</span><br/>
          <span style="color:#2E2E38;font-size:14px;font-weight:600;">${senderName}</span>
        </td>
        <td style="padding:12px 16px;border-bottom:1px solid #eee;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;">Email</span><br/>
          <a href="mailto:${senderEmail}" style="color:#2E2E38;font-size:14px;text-decoration:none;">${senderEmail}</a>
        </td>
      </tr>
      <tr>
        <td style="padding:12px 16px;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;">Job Title</span><br/>
          <span style="color:#2E2E38;font-size:14px;">${senderJobTitle}</span>
        </td>
        <td style="padding:12px 16px;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;">Department</span><br/>
          <span style="color:#2E2E38;font-size:14px;">${senderDepartment}</span>
        </td>
      </tr>
    </table>

    <div style="display:flex;margin-bottom:24px;">
      <div style="flex:1;background:#2E2E38;border-radius:6px;padding:16px;margin-right:8px;text-align:center;">
        <span style="color:rgba(255,255,255,0.6);font-size:11px;text-transform:uppercase;display:block;margin-bottom:4px;">Leave Start</span>
        <span style="color:#FFE600;font-size:16px;font-weight:700;">${formatDate(result.leaveStartDate)}</span>
      </div>
      <div style="flex:1;background:#2E2E38;border-radius:6px;padding:16px;margin-left:8px;text-align:center;">
        <span style="color:rgba(255,255,255,0.6);font-size:11px;text-transform:uppercase;display:block;margin-bottom:4px;">Expected Return</span>
        <span style="color:#FFE600;font-size:16px;font-weight:700;">${formatDate(result.expectedReturnDate)}</span>
      </div>
    </div>

    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:8px;">
      <tr>
        <td style="text-align:center;padding:8px;background:#F9F9F9;border-radius:4px;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;display:block;">Total Days</span>
          <span style="color:#2E2E38;font-size:20px;font-weight:700;">${result.totalCalendarDays}</span>
        </td>
        <td style="width:8px;"></td>
        <td style="text-align:center;padding:8px;background:#F9F9F9;border-radius:4px;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;display:block;">Approx. Weeks</span>
          <span style="color:#2E2E38;font-size:20px;font-weight:700;">${result.totalWeeks}</span>
        </td>
        <td style="width:8px;"></td>
        <td style="text-align:center;padding:8px;background:#F9F9F9;border-radius:4px;">
          <span style="color:#888;font-size:11px;text-transform:uppercase;display:block;">Public Holidays</span>
          <span style="color:#2E2E38;font-size:20px;font-weight:700;">${result.publicHolidaysInPeriod.length}</span>
        </td>
      </tr>
    </table>

    <h3 style="color:#2E2E38;font-size:14px;margin:24px 0 8px;text-transform:uppercase;letter-spacing:0.5px;">Leave Periods</h3>
    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border:1px solid #eee;border-radius:4px;border-collapse:collapse;">
      <tr style="background:rgba(255,230,0,0.1);">
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#2E2E38;text-transform:uppercase;border-bottom:1px solid #eee;">Period</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#2E2E38;text-transform:uppercase;border-bottom:1px solid #eee;">Start</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#2E2E38;text-transform:uppercase;border-bottom:1px solid #eee;">End</th>
        <th style="padding:10px 12px;text-align:center;font-size:11px;color:#2E2E38;text-transform:uppercase;border-bottom:1px solid #eee;">Days</th>
      </tr>
      ${periodsRows}
    </table>

    ${holidaysSection}
  </div>
  <div style="background-color:#F5F5F5;padding:16px 32px;border:1px solid #e0e0e0;border-top:none;border-radius:0 0 4px 4px;">
    <p style="color:#999;font-size:11px;margin:0;line-height:1.5;">
      This is a provisional estimate generated by the EY Family Leave Calculator for planning purposes only.
      It does not replace the formal family leave request process. All employees must submit a standard family leave request in line with firm policies.
      To respond to this submission, please contact the employee at <a href="mailto:${senderEmail}" style="color:#999;">${senderEmail}</a>.
    </p>
  </div>
</div>`;
}

function CalculatorPage() {
  const navigate = useNavigate();
  const [holidays, setHolidays] = useState<Holiday[]>(IRISH_PUBLIC_HOLIDAYS);
  const [holidaysSource, setHolidaysSource] = useState<string>("local");
  const [leaveType, setLeaveType] = useState<LeaveType | "">("");
  const [startDate, setStartDate] = useState("");
  const [durationWeeks, setDurationWeeks] = useState(26);
  const [addUnpaidMaternity, setAddUnpaidMaternity] = useState(false);
  const [unpaidMaternityWeeks, setUnpaidMaternityWeeks] = useState(0);
  const [addParentsLeave, setAddParentsLeave] = useState(false);
  const [parentsLeaveWeeks, setParentsLeaveWeeks] = useState(0);
  const [annualLeaveDays, setAnnualLeaveDays] = useState(0);
  const [result, setResult] = useState<LeaveResult | null>(null);
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [sending, setSending] = useState(false);
  const [sendStatus, setSendStatus] = useState<"idle" | "success" | "error">("idle");

  useEffect(() => {
    fetchHolidays().then((h) => {
      setHolidays(h);
      if (h !== IRISH_PUBLIC_HOLIDAYS) setHolidaysSource("SharePoint");
      else setHolidaysSource("local");
    });
  }, []);

  const canCalculate = leaveType !== "" && startDate !== "";

  const handleCalculate = () => {
    if (!canCalculate) return;
    setSendStatus("idle");
    const res = calculateLeave(
      {
        leaveType: leaveType as LeaveType,
        startDate: new Date(startDate),
        durationWeeks: leaveType === "paternity" ? 2 : durationWeeks,
        unpaidMaternityWeeks:
          leaveType === "maternity" && addUnpaidMaternity
            ? unpaidMaternityWeeks
            : 0,
        parentsLeaveWeeks: addParentsLeave ? parentsLeaveWeeks : 0,
        annualLeaveDays,
      },
      holidays
    );
    setResult(res);
  };

  const handleReset = () => {
    setLeaveType("");
    setStartDate("");
    setDurationWeeks(26);
    setAddUnpaidMaternity(false);
    setUnpaidMaternityWeeks(0);
    setAddParentsLeave(false);
    setParentsLeaveWeeks(0);
    setAnnualLeaveDays(0);
    setResult(null);
    setSendStatus("idle");
  };

  const handleSendToHR = async () => {
    if (!result) return;
    setSending(true);
    setShowConfirmModal(false);

    try {
      const profileResult = await Office365UsersService.MyProfile();
      const profile = profileResult.data;
      const senderName = profile?.DisplayName || "Employee";
      const senderEmail = profile?.Mail || profile?.UserPrincipalName || "";
      const senderJobTitle = profile?.JobTitle || "Not specified";
      const senderDepartment = profile?.Department || "Not specified";
      const typeLabel = leaveType === "maternity" ? "Maternity" : "Paternity";

      await Office365OutlookService.SendEmailV2({
        To: HR_EMAIL,
        Cc: senderEmail || undefined,
        Subject: `${typeLabel} Leave Breakdown - ${senderName} - ${formatDate(result.leaveStartDate)} to ${formatDate(result.expectedReturnDate)}`,
        Body: buildBreakdownEmailHtml(
          result,
          leaveType as string,
          senderName,
          senderEmail,
          senderJobTitle,
          senderDepartment
        ),
        Importance: "Normal",
      });
      setSendStatus("success");
    } catch {
      setSendStatus("error");
    } finally {
      setSending(false);
    }
  };

  return (
    <div className="calculator-page">
      <TopBar />
      <main className="calc-main">
        <div className="calc-container">
          <button className="back-link" onClick={() => navigate("/")}>
            &larr; Back to Home
          </button>
          <h1 className="calc-title">Family Leave Calculator</h1>
          <p className="calc-subtitle">
            Enter your details below to estimate your leave dates and
            provisional return to work date.
            <span className="data-source-badge">{holidaysSource === "SharePoint" ? "Holidays: SharePoint" : "Holidays: Local"}</span>
          </p>

          <div className="calc-form">
            {/* Step 1: Leave Type */}
            <div className="form-section">
              <label className="form-label">
                <span className="step-number">1</span>
                Type of Leave
              </label>
              <select
                className="form-select"
                value={leaveType}
                onChange={(e) => {
                  setLeaveType(e.target.value as LeaveType | "");
                  if (e.target.value === "paternity") {
                    setAddUnpaidMaternity(false);
                    setUnpaidMaternityWeeks(0);
                  }
                  setResult(null);
                  setSendStatus("idle");
                }}
              >
                <option value="">-- Select leave type --</option>
                <option value="maternity">Maternity Leave</option>
                <option value="paternity">Paternity Leave</option>
              </select>
            </div>

            {/* Step 2: Start Date */}
            {leaveType && (
              <div className="form-section">
                <label className="form-label">
                  <span className="step-number">2</span>
                  Leave Start Date
                </label>
                <input
                  type="date"
                  className="form-input"
                  value={startDate}
                  onChange={(e) => {
                    setStartDate(e.target.value);
                    setResult(null);
                    setSendStatus("idle");
                  }}
                />
              </div>
            )}

            {/* Step 3: Duration */}
            {leaveType && startDate && (
              <div className="form-section">
                <label className="form-label">
                  <span className="step-number">3</span>
                  Leave Duration
                </label>
                {leaveType === "maternity" ? (
                  <>
                    <select
                      className="form-select"
                      value={durationWeeks}
                      onChange={(e) => {
                        setDurationWeeks(Number(e.target.value));
                        setResult(null);
                      }}
                    >
                      {Array.from({ length: 21 }, (_, i) => i + 6).map(
                        (w) => (
                          <option key={w} value={w}>
                            {w} weeks
                          </option>
                        )
                      )}
                    </select>
                    <p className="form-hint">
                      Maternity leave can be between 6 and 26 weeks.
                    </p>
                  </>
                ) : (
                  <div className="info-box">
                    <strong>2 weeks</strong> (10 working days) — Paternity leave
                    duration is fixed.
                  </div>
                )}
              </div>
            )}

            {/* Step 4: Unpaid Maternity (maternity only) */}
            {leaveType === "maternity" && startDate && (
              <div className="form-section">
                <label className="form-label">
                  <span className="step-number">4</span>
                  Additional Unpaid Maternity Leave?
                </label>
                <div className="toggle-row">
                  <button
                    className={`toggle-btn ${addUnpaidMaternity ? "active" : ""}`}
                    onClick={() => {
                      setAddUnpaidMaternity(!addUnpaidMaternity);
                      if (addUnpaidMaternity) setUnpaidMaternityWeeks(0);
                      else setUnpaidMaternityWeeks(1);
                      setResult(null);
                    }}
                  >
                    {addUnpaidMaternity ? "Yes" : "No"}
                  </button>
                  <span className="form-hint-inline">
                    Up to 16 weeks unpaid leave
                  </span>
                </div>
                {addUnpaidMaternity && (
                  <select
                    className="form-select"
                    value={unpaidMaternityWeeks}
                    onChange={(e) => {
                      setUnpaidMaternityWeeks(Number(e.target.value));
                      setResult(null);
                    }}
                  >
                    {Array.from({ length: 16 }, (_, i) => i + 1).map((w) => (
                      <option key={w} value={w}>
                        {w} week{w > 1 ? "s" : ""}
                      </option>
                    ))}
                  </select>
                )}
              </div>
            )}

            {/* Step 5: Parents Leave */}
            {leaveType && startDate && (
              <div className="form-section">
                <label className="form-label">
                  <span className="step-number">
                    {leaveType === "maternity" ? "5" : "4"}
                  </span>
                  Parents Leave?
                </label>
                <div className="toggle-row">
                  <button
                    className={`toggle-btn ${addParentsLeave ? "active" : ""}`}
                    onClick={() => {
                      setAddParentsLeave(!addParentsLeave);
                      if (addParentsLeave) setParentsLeaveWeeks(0);
                      else setParentsLeaveWeeks(1);
                      setResult(null);
                    }}
                  >
                    {addParentsLeave ? "Yes" : "No"}
                  </button>
                  <span className="form-hint-inline">
                    Up to 9 weeks (applies to both Maternity and Paternity)
                  </span>
                </div>
                {addParentsLeave && (
                  <select
                    className="form-select"
                    value={parentsLeaveWeeks}
                    onChange={(e) => {
                      setParentsLeaveWeeks(Number(e.target.value));
                      setResult(null);
                    }}
                  >
                    {Array.from({ length: 9 }, (_, i) => i + 1).map((w) => (
                      <option key={w} value={w}>
                        {w} week{w > 1 ? "s" : ""}
                      </option>
                    ))}
                  </select>
                )}
              </div>
            )}

            {/* Step 6: Annual Leave */}
            {leaveType && startDate && (
              <div className="form-section">
                <label className="form-label">
                  <span className="step-number">
                    {leaveType === "maternity" ? "6" : "5"}
                  </span>
                  Annual Leave Days
                </label>
                <input
                  type="number"
                  className="form-input"
                  min={0}
                  max={50}
                  value={annualLeaveDays}
                  onChange={(e) => {
                    setAnnualLeaveDays(
                      Math.max(0, Math.min(50, Number(e.target.value)))
                    );
                    setResult(null);
                  }}
                />
                <p className="form-hint">
                  Working days only (Mon-Fri). Ensure these days are available to
                  you.
                </p>
              </div>
            )}

            {/* Actions */}
            {canCalculate && (
              <div className="calc-actions">
                <button
                  className="ey-button primary"
                  onClick={handleCalculate}
                >
                  Calculate Return Date
                </button>
                <button className="ey-button secondary" onClick={handleReset}>
                  Reset
                </button>
              </div>
            )}
          </div>

          {/* Results */}
          {result && (
            <div className="calc-results">
              <h2 className="results-title">Provisional Leave Breakdown</h2>

              <div className="results-highlight">
                <div className="highlight-card">
                  <span className="highlight-label">Leave Start Date</span>
                  <span className="highlight-value">
                    {formatDate(result.leaveStartDate)}
                  </span>
                </div>
                <div className="highlight-card return-date">
                  <span className="highlight-label">
                    Expected Return to Work
                  </span>
                  <span className="highlight-value">
                    {formatDate(result.expectedReturnDate)}
                  </span>
                </div>
              </div>

              <div className="results-summary">
                <div className="summary-item">
                  <span className="summary-label">Total Calendar Days</span>
                  <span className="summary-value">
                    {result.totalCalendarDays}
                  </span>
                </div>
                <div className="summary-item">
                  <span className="summary-label">Approx. Weeks</span>
                  <span className="summary-value">{result.totalWeeks}</span>
                </div>
                <div className="summary-item">
                  <span className="summary-label">
                    Public Holidays in Period
                  </span>
                  <span className="summary-value">
                    {result.publicHolidaysInPeriod.length}
                  </span>
                </div>
              </div>

              <h3 className="section-title">Leave Periods</h3>
              <div className="periods-table">
                <div className="period-header">
                  <span>Period</span>
                  <span>Start</span>
                  <span>End</span>
                  <span>Days</span>
                </div>
                {result.periods.map((p, i) => (
                  <div className="period-row" key={i}>
                    <span className="period-label">{p.label}</span>
                    <span>{formatDate(p.startDate)}</span>
                    <span>{formatDate(p.endDate)}</span>
                    <span className="period-days">{p.calendarDays}</span>
                  </div>
                ))}
              </div>

              {result.publicHolidaysInPeriod.length > 0 && (
                <>
                  <h3 className="section-title">
                    Public Holidays During Leave
                  </h3>
                  <div className="holidays-list">
                    {result.publicHolidaysInPeriod.map((h, i) => (
                      <div className="holiday-row" key={i}>
                        <span className="holiday-date">
                          {formatDate(h.date)}
                        </span>
                        <span className="holiday-name">{h.name}</span>
                      </div>
                    ))}
                  </div>
                  <p className="holiday-note">
                    Each public holiday extends your leave by one additional
                    day.
                  </p>
                </>
              )}

              <div className="results-disclaimer">
                <p>
                  This is a provisional estimate for planning purposes only. It
                  does not replace the formal family leave request process.
                  Please submit a standard family leave request in line with
                  firm policies.
                </p>
              </div>

              {/* Send to HR */}
              <div className="send-hr-section">
                {sendStatus === "success" ? (
                  <div className="send-success">
                    <svg width="24" height="24" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <circle cx="24" cy="24" r="20" fill="#ffe600" opacity="0.2" />
                      <path d="M16 24L22 30L34 18" stroke="#ffe600" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                    <span>Breakdown sent to HR Services. A copy has been sent to your email.</span>
                  </div>
                ) : sendStatus === "error" ? (
                  <div className="send-error">
                    Failed to send. Please try again.
                  </div>
                ) : null}
                <button
                  className="ey-button send-hr-btn"
                  onClick={() => setShowConfirmModal(true)}
                  disabled={sending || sendStatus === "success"}
                >
                  {sending ? "Sending..." : sendStatus === "success" ? "Sent" : "Send Breakdown to HR Services"}
                </button>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Confirmation Modal */}
      {showConfirmModal && (
        <div className="modal-overlay" onClick={() => setShowConfirmModal(false)}>
          <div className="modal-content confirm-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Confirm Submission</h2>
              <button className="modal-close" onClick={() => setShowConfirmModal(false)}>
                &times;
              </button>
            </div>
            <div className="modal-body">
              <div className="confirm-icon">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <circle cx="24" cy="24" r="20" stroke="#ffe600" strokeWidth="2" fill="none" />
                  <path d="M24 14V28" stroke="#ffe600" strokeWidth="3" strokeLinecap="round" />
                  <circle cx="24" cy="34" r="2" fill="#ffe600" />
                </svg>
              </div>
              <p className="confirm-text">
                Are you sure you want to send this leave breakdown to HR Services?
              </p>
              <p className="confirm-details">
                The email will be sent to <strong>{HR_EMAIL}</strong> and a copy will be sent to your email address.
                This is for planning purposes only and does not constitute a formal leave request.
              </p>
            </div>
            <div className="modal-footer">
              <button className="modal-button discard" onClick={() => setShowConfirmModal(false)}>
                Cancel
              </button>
              <button className="modal-button send" onClick={handleSendToHR}>
                Yes, Send to HR
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default CalculatorPage;